import { Container, Flex, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./auth/Provider";
import "./globals.css";
import NavBar from "./NavBar";
import "./theme-config.css";
import QueryClientProvider from "@/QueryClientProvider";
import Link from "next/link";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<QueryClientProvider>
				<body className={inter.variable}>
					<AuthProvider>
						<Theme accentColor='purple'>
							<NavBar />
							<main className='p-5'>
								<Container>{children}</Container>
							</main>
							<footer>
								<Flex direction='row' gap='3' justify='center' mt='9'>
									<Link href='/privacy' className='text-sm'>
										privacy
									</Link>
									<Link href='/terms' className='text-sm'>
										terms
									</Link>
								</Flex>
							</footer>
						</Theme>
					</AuthProvider>
				</body>
			</QueryClientProvider>
		</html>
	);
}
